# Generated by Django 3.1.7 on 2021-03-27 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210327_0356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
