# Generated by Django 3.1.7 on 2021-03-27 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210327_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catergory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kind', to='auctions.category'),
        ),
    ]
