# Generated by Django 3.1.7 on 2021-03-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210327_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_name',
            new_name='listing_title',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing',
            field=models.TextField(null=True),
        ),
    ]
