# Generated by Django 3.1.7 on 2021-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210327_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
