# Generated by Django 3.1.7 on 2021-03-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210327_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
