# Generated by Django 3.1.7 on 2021-03-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210328_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_owner',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
