# Generated by Django 3.1.7 on 2021-03-28 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210328_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='listing_category',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='listing_image',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='listing_price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='listing_title',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='listing_user',
        ),
    ]
