# Generated by Django 3.1.7 on 2021-03-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20210328_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
    ]
