# Generated by Django 3.1.7 on 2021-03-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20210329_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
