# Generated by Django 3.1.7 on 2021-03-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20210329_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
