# Generated by Django 3.1.7 on 2021-03-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20210329_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
