# Generated by Django 3.1.7 on 2021-03-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_auto_20210330_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_price', to='auctions.listing'),
        ),
    ]
