# Generated by Django 3.1.7 on 2021-03-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_auto_20210330_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
