# Generated by Django 3.1.7 on 2021-04-02 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0058_auto_20210403_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='in_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
